config/routes.rb
Rails.application.routes.draw do
  root to: 'power_generators#index'
  resources :home, only: %i[index]
  resources :power_generators do
    collection do
      get 'get_freight'
      get 'filter'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/freight.rb
class Freight < ApplicationRecord
  validates :state, :weight_min, :weight_max, :cost, presence: true
end

app/models/power_generator.rb
class PowerGenerator < ApplicationRecord
  validates :name, :description, :image_url, :manufacturer, :price, :kwp, presence: true
  validates :height, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 40 }
  validates :width, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :lenght, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 200 }
  validates :weight, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 3000 }

  enum structure_type: %i[
    metalico
    ceramico
    fibrocimento
    laje
    solo
    trapezoidal
  ]

  paginates_per(6)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/power_generators_controller.rb
class PowerGeneratorsController < ApplicationController
  def index
    @power_generators = PowerGenerator.order(name: :asc).page params[:page]
    @keyword = params["keyword"]
    
    unless params["keyword"].blank?
      @power_generators = @power_generators.where("name LIKE ?", "%" + @keyword.parameterize.upcase + "%").order(name: :asc).page params[:page]
    end

    # unless params["income"].blank? && params["postal_code"].blank? && params["wish_price"].blank? && params["performance"].blank?
    #   product_recommendation
    # end
  end

  def filter
    if params["filter"] == "price"
      @power_generators = PowerGenerator.order(price: :asc).page params[:page]
    elsif params["filter"] == "name"
      @power_generators = PowerGenerator.order(name: :asc).page params[:page]
    elsif params["filter"] == "kwp"
      @power_generators = PowerGenerator.order(kwp: :asc).page params[:page]
    else
      @power_generators = PowerGenerator.order(name: :asc).page params[:page]
    end

    render :index
  end

  def get_freight
    address = Correios::CEP::AddressFinder.new.get(params["postal_code"])

    pg_data = PowerGenerator.where(id: params["pg_id"]).first
    if pg_data.cubed_weight.blank?
      create_cubed_weight pg_data
    end
    weight = pg_data.weight
    freight = Freight.where("state = ? AND weight_min <= ? AND weight_max >= ?", address[:state], weight, weight)

    address.merge!({:freight_cost => freight.first.cost, :cubed_weight => pg_data.cubed_weight})

    respond_to do |format|
      format.json {render json: address}
    end
  end

  private
    def product_recommendation
      # unless params["postal_code"].blank?
      #   address = Correios::CEP::AddressFinder.new.get(params["postal_code"])
      # end
      # weight = PowerGenerator.where(id: params["pg_id"]).first

      # params["income"]
      # params["wish_price"]
      # params["performance"]
    end

    def create_cubed_weight pg_data
      height = pg_data.height
      weight = pg_data.weight
      lenght = pg_data.lenght
      cubed_factor = 300

      cubed_weight = height * weight * lenght * cubed_factor

      pg_data.update_attribute(:cubed_weight, cubed_weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal Solar - Dev Test</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/power_generators/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="freightModal" tabindex="-1" role="dialog" aria-labelledby="freightModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="freightModalLabel">Calculo de Frete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="cep">CEP</label>
              <input type="text" class="form-control" id="cep" name="postal_code">
            </div>
             <div class="form-group col-md-6">
              <p><strong id="zipcode_notfound_msg" style="display:none;color: red;">Endereço não encontrado, tente outro CEP</strong></p>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="street">Rua</label>
              <input type="text" class="form-control" id="street" readonly>
            </div>
            <div class="form-group col-md-6">
              <label for="neighborhood">Bairro</label>
              <input type="text" class="form-control" id="neighborhood" readonly>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-10">
              <label for="city">Cidade</label>
              <input type="text" class="form-control" id="city" readonly>
            </div>
            <div class="form-group col-md-2">
              <label for="state">Estado</label>
              <input type="text" class="form-control" id="state" readonly>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="state">Preço do frete em Reais(R$)</label>
              <input type="text" class="form-control" id="freight_price" value="0,00" readonly>
            </div>
            <div class="form-group col-md-6">
              <label for="state">Peso Cubado</label>
              <input type="text" class="form-control" id="cubed_weight" value="0,00" readonly>
            </div>
          </div>
          <input type="hidden" id="pg_id_send" name="pg_id">
      </div>
      <div class="modal-footer">
          <button id="calc_freight_btn" class="btn btn-outline-success">Calcular Frete</button>
      </div>
    </div>
  </div>
</div>

app/views/power_generators/index.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light searcher gradient">
    <a class="navbar-brand" href="/"><%= image_tag 'ps_logo.png', class: "logo" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group-vertical btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-secondary active">
              <input type="radio" name="searchRadio" id="simple_search" value="simple" checked> Busca Simples
            </label>
            <label class="btn btn-secondary">
              <input type="radio" name="searchRadio" id="advanced_search" value="advanced"> Busca Avançada
            </label>
          </div>
        </div>
      </div>
      <%= form_tag root_path, method: "get", class: "form-inline" do %>
        <div class="row">
          <div class="col-md-12">
            <div class="simple-form">
              <input id="simple_search_field" class="form-control simple_search" type="search" name="keyword" placeholder="o que procura?" aria-label="Search" checked="true">
            </div>
          </div>
          <div class="col-md-12">  
            <div class="advanced-form" style="display:none;">
              <div class="row">
                <div class="col">
                  <input id="income" class="form-control advanced_field" type="search" name="income" placeholder="renda mensal" aria-label="Search">
                </div>
                <div class="col">
                  <input id="postal_code" class="form-control advanced_field" type="search" name="postal_code" placeholder="CEP" aria-label="Search">
                </div>
                <div class="col">
                  <input id="wish_price" class="form-control advanced_field" type="search" name="wish_price" placeholder="Preço Desejado Aproximado" aria-label="Search">
                </div>
              </div>
              <div class="row">
                <div class="col-md-10">
                  <select class="custom-select advanced_field" id="performance" name="performance">
                    <option selected>Eficiência...</option>
                    <option value="low">Baixa</option>
                    <option value="medium">Média</option>
                    <option value="high">Alta</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Buscar </button>
          </div>
        </div>
      <% end %>
    </div>
  </nav>
  <div class="row">
    <div class="col mt-3">
      <%= paginate @power_generators %>
    </div>
    <div class="col mt-3">
      <%= form_tag filter_power_generators_path, method: "get", class: "form-inline" do %>
        <select class="custom-select mr-sm-2" id="filter" name="filter">
          <option selected>Ordenar Por...</option>
          <option value="price">Preço</option>
          <option value="name">Nome</option>
          <option value="kwp">KWP</option>
        </select>

        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ordenar </button>
      <% end %>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-4">
    <%if @power_generators.blank? %>
      Não Encontramos registros com esse nome. Por favor, busque um nome válido.
    <%else%>
      <% @power_generators.each do |power_generator| %>
        <div class="col mb-4">
          <div class="card">
            <div class="card-header">
              <%= image_tag power_generator.image_url, class: 'card-img-top card_img' %>
            </div>
            <div class="card-body">
              <h2><%= power_generator.name %></h2>
              <p class="card-title card_price"><%= number_to_currency(power_generator.price, unit: "R$ ", precision: 2, separator: ",", delimiter: ".", class: "card_price") %></p>
              <button type="button" class="card-link btn btn-outline-success modal_btn" data-toggle="modal" data-target="#freightModal" data-whatever="">Consultar as melhores condições de Entrega</button>
              <div class="card-footer">
                <p class="card-text"><strong>Descrição: </strong><%= power_generator.description %></p>
              </div>
              <input type="hidden" class="pg_id" name="id" value="<%= power_generator.id %>">
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= render "power_generators/modal" %>
</div>